name: Build and Package

on: [push]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3.3.0

    - name: Build Docker Image
      run: |
        docker build -t messagingmicroservice .
        
    - name: Save Docker Image
      run: |
        docker save messagingmicroservice > messagingmicroservice.tar

    - name: Upload Docker Image
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.KEY }}
        source: messagingmicroservice.tar
        target: /root/Docker/
        
    - name: Stop And Remove Current Container
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          running=$(docker ps --filter name=messagingmicroservice --format '{{.Names}}')
          if [[ $running == messagingmicroservice ]]; then
            docker stop messagingmicroservice
            docker rm messagingmicroservice
          fi
    - name: Load New Docker Image
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          docker load -i /root/Docker/messagingmicroservice.tar

    - name: Start New Container
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          docker run -d -p 5002:80 --mount type=bind,source="${{ secrets.FILE_PATH }}",target=/app/Logs --env MMSConnString='${{ secrets.ENV }}' --name messagingmicroservice messagingmicroservice:latest

    - name: Clean Up The Tar File
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          rm /root/Docker/messagingmicroservice.tar